FORMAT: 1A
HOST: http://youtubesweg.me 

# YouTubeSWEg

RESTful API to expose data regarding YouTube videos presented from youtubesweg.me.

## Video [/api/video/{?id,channel_id,category_id}]

### List Videos [GET]

Returns videos from the website. If no optional parameters are provided, all the videos will be returned.

Supply only one of the following optional parameters:  
    - id  
    - channel\_id  
    - category\_id  
    
Providing more than one optional parameter will be considered a malformed request.  

Note: the channel_id field and categories field both contain integer values to indicate the channel 
or category respectively. Query the Channel or Category resource again with the ID in order to receive 
the respective object.

+ Parameters
    + id (optional) - [Integer] ID of a specific video. If this parameter is provided, only the specific video 
        indicated by this ID will be returned in the videos array. There will be at most 1 result.
    + channel_id (optional) - [Integer] ID of a specific channel. If this parameter is provided, only specific videos 
        present in the channel indicated by this ID will be returned in the videos array. There may be multiple results.
    + category_id (optional) - [Integer] ID of a specific category. If this parameter is provided, only specific videos
        present in the category specified by this ID will be returned in the videos array. There may be multiple results.
        
+ Response 200 (application/json)

        [
            {
                "num_videos": 2,
                "videos": [
                    {
                        "title": "video1 title",
                        "description": "video1 description",
                        "thumbnail": "https://i.ytimg.com/vi/xwf08LmchUY/default.jpg",
                        "channel_id": 1,
                        "id": 1,
                        "tags": [
                            "tag1",
                            "tag2"
                        ],
                        "category": 5
                    }, {
                        "title": "video2 title",
                        "description": "video2 description",
                        "thumbnail": "https://i.ytimg.com/vi/sIQ4ng0e1GU/default.jpg",
                        "id": 2,
                        "channel_id": 2,
                        "tags": [
                            "tag5",
                            "tag3"
                        ],
                        "category": 3
                    }
                ]
            }
        ]
        
## Channel [/api/channel/{?id,country}]

### List Channels [GET]

Returns channels from the website. If no optional parameters are provided, all the channels will be returned.

Supply only one of the following optional parameters:  
    - id  
    - country  

Providing more than one optional parameter will be considered a malformed request.  

Note: the videos field and playlists field both contain an array of integer values to 
indicate the videos or playlists respectively. Query the Video or Playlist 
resource again with the ID in order to receive the respective object.

+ Parameters
    + id (optional) - [Integer] ID of a specific channel. If this parameter is provided, only the specific channel 
        indicated by this ID will be returned in the channels array. There will be at most 1 result.
    + country (optional) - [String] Country code in the ISO 3166-1 alpha-2 format (ex. US). If this parameter 
        is provided, only specific channels present in the country indicated by this code will be 
        returned in the channels array. There may be multiple results.
    

+ Response 200 (application/json)

        [
            {
                "num_channels": 1,
                "channels": [
                    {
                        "title": "channel title",
                        "description": "channel description",
                        "published_date": "2017-03-17T01:00:03.000Z",
                        "country": "US",
                        "view_count": 10000,
                        "subscriber_count": 100,
                        "id": 2,
                        "videos": [
                            1,
                            2
                        ],
                        "playlists": [
                            3,
                            4
                        ]
                    }
                ]
            }
        ]
        
## Category [/api/category/{?id,channel_id}]

### List Categories [GET]

Returns categories from the website. If no optional parameters are provided, all the categories will be returned.

Supply only one of the following optional parameters:  
    - id  
    - channel\_id  

Providing more than one optional parameter will be considered a malformed request.  

Note: the videos field and channels field both contain an array of integer values to 
indicate the videos or channels respectively. Query the Video or Channel 
resource again with the ID in order to receive the respective object.

+ Parameters
    + id (optional) - [Integer] ID of a specific category. If this parameter is provided, only the specific category 
        indicated by this ID will be returned in the categories array. There will be at most 1 result.
    + channel_id (optional) - [Integer] ID of a specific channel. If this parameter is provided, only specific categories 
        containing videos from the channel indicated by this ID will be returned in the categories array. There may be multiple results.

+ Response 200 (application/json)

        [
            {
                "num_category": 1,
                "categories": [
                    {
                        "title": "category title",
                        "published_date": "2017-03-17T01:00:03.000Z",
                        "num_videos": 100,
                        "assignable": false,
                        "id": 3,
                        "videos": [
                            1,
                            2
                        ],
                        "channels": [
                            3,
                            4
                        ]
                    }
                ]
            }
        ]
        
## Playlist [/api/playlist/{?id,video_id}]

### List Playlists [GET]

Returns playlists from the website. If no optional parameters are provided, all the playlists will be returned.

Supply only one of the following optional parameters:  
    - id  
    - video\_id  

Providing more than one optional parameter will be considered a malformed request.  

Note: the channel_id field and videos field both contain integer values to 
indicate the channel or videos respectively. Query the Channel or Video 
resource again with the ID in order to receive the respective object.

+ Parameters
    + id (optional) - [Integer] ID of a specific playlist. If this parameter is provided, only the specific playlist 
        indicated by this ID will be returned in the playlists array. There will be at most 1 result.
    + video_id (optional) - [Integer] ID of a specific channel. If this parameter is provided, only specific playlists 
        containing the video indicated by this ID will be returned in the playlists array. There may be multiple results.

+ Response 200 (application/json)

        [
            {
                "num_playlists": 1,
                "playlists": [
                    {
                        "title": "playlist title",
                        "description": "playlist description",
                        "published_date": "2017-03-17T01:00:03.000Z",
                        "num_items": 100,
                        "channel_id": 1,
                        "id": 5,
                        "videos": [
                            3,
                            4
                        ]
                    }
                ]
            }
        ]